---
pull_request_rules:
  - name: Auto-squash dependabot updates when checks pass
    conditions:
      - and:
          - author=dependabot[bot]
          - label!=wontfix
          - check-success=SonarCloud Code Analysis
          - check-success=Build
          - check-success=MegaLinter
          - check-success=Test
          - or:
              - check-success=CodeQL
              - check-neutral=CodeQL
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: merge
  - name: Auto-squash when all checks pass and the PR has been approved
    conditions:
      - and:
          - "#approved-reviews-by>=1"
          - check-success=SonarCloud Code Analysis
          - check-success=Build
          - check-success=MegaLinter
          - check-success=Test
          - or:
              - check-success=CodeQL
              - check-neutral=CodeQL
    actions:
      merge:
        method: merge
  - name: Get some eyes on it
    conditions:
      - -draft
      - author!=dependabot[bot]
    actions:
      request_reviews:
        users:
          - JoshTheWanderer
          - DanWebb
          - gavmck
          - ella-etch
          - Carl-J-M
        random_count: 2
  - name: Assign the PR to its author
    conditions:
      - author!=dependabot[bot]
    actions:
      assign:
        users:
          - "{{author}}"
