---
pull_request_rules:
  - name: Auto-squash dependabot updates when checks pass
    conditions:
      - and:
          - author=dependabot[bot]
          - label!=wontfix
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: merge
  - name: Auto-squash when all checks pass and the PR has been approved
    conditions:
      - and:
          - "#approved-reviews-by>=1"
          - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
  - name: Get some eyes on it
    conditions:
      - -closed
      - -draft
      - author!=dependabot[bot]
    actions:
      request_reviews:
        teams:
          - devs
        random_count: 2
  - name: Assign the PR to its author
    conditions:
      - author!=dependabot[bot]
    actions:
      assign:
        users:
          - "{{author}}"
