---
pull_request_rules:
  - name: Auto-squash dependabot updates when checks pass
    conditions:
      - and:
          - author~=^dependabot(|-preview)\[bot\]$
          - label!=wontfix
          - check-success=SonarCloud Code Analysis
          - check-success=build
          - check-success=lint
          - check-success=test
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: merge
  - name: Auto-squash when all checks pass and the PR has been approved
    conditions:
      - and:
          - check-success=SonarCloud Code Analysis
          - check-success=build
          - check-success=lint
          - check-success=test
          - "#review-requested=0"
          - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Get some eyes on it
    conditions:
      - -closed
      - -draft
      - author~=!^dependabot(|-preview)\[bot\]$
    actions:
      request_reviews:
        users:
          - JoshTheWanderer
          - DanWebb
          - gavmck
          - ella-etch
          - Carl-J-M
        random_count: 2
  - name: Assign the PR to its author
    conditions:
      - author~=!^dependabot(|-preview)\[bot\]$
    actions:
      assign:
        users:
          - {{author}}
