# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: none

DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  # We use stylelint for CSS and SCSS linting
  - CSS_SCSS_LINT
  # Disable in favour of eslint
  - JAVASCRIPT_STANDARD
  # We use dependabot for vulnerability monitoring and patching
  - REPOSITORY_GRYPE
  # Not needed in this repository
  - REPOSITORY_TRIVY
  # Disable in favour of eslint
  - TYPESCRIPT_STANDARD

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Config paths
CSS_STYLELINT_CONFIG_FILE: stylelint.config.js
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json

# Executable overrides
CSS_STYLELINT_CLI_EXECUTABLE: ['./node_modules/.bin/stylelint']
